import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/app/lib/mongodb';
import { ObjectId } from 'mongodb';
import { Resend } from 'resend';

export async function POST(req: NextRequest) {
  try {
    const { reference } = await req.json();
    if (!reference) {
      return NextResponse.json({ error: 'Missing reference' }, { status: 400 });
    }

    const username = process.env.FASTSPRING_USERNAME;
    const password = process.env.FASTSPRING_PASSWORD;

    if (!username || !password) {
      return NextResponse.json({ error: 'FastSpring credentials missing' }, { status: 500 });
    }

    const credentials = Buffer.from(`${username}:${password}`).toString('base64');
    
    // Fetch from FastSpring API
    const fsResponse = await fetch(`https://api.fastspring.com/orders/${reference}`, {
      method: 'GET',
      headers: {
        Authorization: `Basic ${credentials}`,
        Accept: 'application/json',
      },
    });

    if (!fsResponse.ok) {
      return NextResponse.json({ error: 'Order not found in FastSpring' }, { status: 404 });
    }

    const orderData = await fsResponse.json();
    
    // Verify FastSpring actually marks this as a completed order
    if (orderData.completed !== true) {
      return NextResponse.json({ status: 'pending', message: 'Order not yet completed in FastSpring' });
    }

    const tags = orderData.tags || {};
    const localOrderId = tags.localOrderId;

    const { db } = await connectToDatabase();

    // Helper to send success email
    const sendSuccessEmail = async (customerName: string, customerEmail: string, amount: string | number, planDetails: string) => {
      if (process.env.RESEND_API_KEY) {
        try {
          const resend = new Resend(process.env.RESEND_API_KEY);
          await resend.emails.send({
            from: 'notifications@qualitybusinesstech.us',
            to: 'info@qualitybusinesstech.us',
            subject: `New Successful Payment: $${amount} from ${customerName}`,
            html: `
              <h2>New Successful Payment Received</h2>
              <p><strong>Customer Name:</strong> ${customerName}</p>
              <p><strong>Customer Email:</strong> ${customerEmail}</p>
              <p><strong>Amount Paid:</strong> $${amount} USD</p>
              <p><strong>Plan / Product:</strong> ${planDetails}</p>
              <p><strong>FastSpring Order Ref:</strong> ${orderData.reference}</p>
              <hr />
              <p><small>This notification was automatically generated by your QuickBooks Enterprise payment portal.</small></p>
            `
          });
          console.log('[Sync Order] Success email sent via Resend');
        } catch (e) {
          console.error('[Sync Order] Failed to send Resend email', e);
        }
      } else {
        console.warn('[Sync Order] RESEND_API_KEY not found in environment. Email not sent.');
      }
    };
    
    // 1. If we have a localOrderId, try to update the existing Pending record
    if (localOrderId) {
      try {
        const existingRecord = await db.collection('admindata').findOne({ _id: new ObjectId(localOrderId) });
        
        if (existingRecord) {
          if (existingRecord.status === 'Completed') {
            return NextResponse.json({ status: 'already_synced' });
          }

          const amountUSD = parseFloat(orderData.total || existingRecord.amountUSD);

          await db.collection('admindata').updateOne(
            { _id: new ObjectId(localOrderId) },
            {
              $set: {
                status: 'Completed',
                fsOrderReference: orderData.reference,
                fsOrderId: orderData.id,
                paidAt: new Date(),
                amountUSD: amountUSD,
              }
            }
          );

          // Send notification
          const customerName = `${existingRecord.firstName || ''} ${existingRecord.lastName || ''}`.trim() || 'Unknown Customer';
          await sendSuccessEmail(customerName, existingRecord.email || '', amountUSD, existingRecord.planDetails || 'Unknown Plan');

          return NextResponse.json({ status: 'synced', localOrderId });
        }
      } catch (e) {
        console.warn('[Sync Order] localOrderId was invalid or not found, falling back to insert');
      }
    }

    // 2. Fallback: If pending record is missing or localOrderId wasn't saved, insert a new record directly from tags
    // Check if we already synced this order reference to avoid duplicates
    const existingRef = await db.collection('admindata').findOne({ fsOrderReference: orderData.reference });
    if (existingRef) {
      return NextResponse.json({ status: 'already_synced' });
    }

    const amountUSD = parseFloat(tags.amountUSD || orderData?.total || '0');
    const planDetails = tags.planDetails || ('QuickBooks Enterprise (Order Ref: ' + (orderData?.reference || 'Unknown') + ')');
    const email = tags.email || orderData?.customer?.email || '';
    const firstName = tags.firstName || orderData?.customer?.firstName || '';
    const lastName = tags.lastName || orderData?.customer?.lastName || '';
    
    const newRecord = {
      email,
      firstName,
      lastName,
      companyName: tags.companyName || orderData?.customer?.company || '',
      phone: tags.phone || orderData?.customer?.phone || '',
      address: tags.address || orderData?.customer?.address?.addressLine1 || '',
      city: tags.city || orderData?.customer?.address?.city || '',
      state: tags.state || orderData?.customer?.address?.region || '',
      zipCode: tags.zipCode || orderData?.customer?.address?.postalCode || '',
      country: tags.country || orderData?.customer?.address?.country || 'US',
      ipAddress: tags.ipAddress || orderData?.ip || '127.0.0.1',
      browser: tags.browser || 'Unknown',
      deviceType: tags.deviceType || 'Desktop',
      amountUSD,
      planDetails,
      agreedToTerms: tags.agreedToTerms === 'true' || true,
      agreedTimestamp: tags.agreedTimestamp ? new Date(tags.agreedTimestamp) : new Date(),
      status: 'Completed',
      fsOrderReference: orderData.reference || '',
      fsOrderId: orderData.id || '',
      paidAt: new Date(),
      createdAt: new Date(),
    };
    
    await db.collection('admindata').insertOne(newRecord);

    // Send notification
    const customerName = (firstName + ' ' + lastName).trim() || 'Unknown Customer';
    await sendSuccessEmail(customerName, email, amountUSD, planDetails);

    return NextResponse.json({ status: 'recreated_and_synced' });

  } catch (error: any) {
    console.error('[Sync Order Error]', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
