import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/app/lib/mongodb';
import { ObjectId } from 'mongodb';
import { Resend } from 'resend';

export async function POST(req: NextRequest) {
  try {
    const { transactionId, localOrderId } = await req.json();

    if (!transactionId || !localOrderId) {
      return NextResponse.json({ error: 'Missing parameters' }, { status: 400 });
    }

    const apiLoginId = process.env.AUTHORIZE_NET_API_LOGIN_ID;
    const transactionKey = process.env.AUTHORIZE_NET_TRANSACTION_KEY;
    const isProd = process.env.AUTHORIZE_NET_IS_PRODUCTION === 'true';

    if (!apiLoginId || !transactionKey) {
      return NextResponse.json({ error: 'Authorize.net credentials missing' }, { status: 500 });
    }

    const endpoint = isProd 
      ? 'https://api.authorize.net/xml/v1/request.api'
      : 'https://apitest.authorize.net/xml/v1/request.api';

    const verifyBody = {
      getTransactionDetailsRequest: {
        merchantAuthentication: {
          name: apiLoginId,
          transactionKey: transactionKey
        },
        transId: transactionId
      }
    };

    const fsResponse = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(verifyBody),
    });

    const data = await fsResponse.json();

    if (data.messages.resultCode !== 'Ok' || !data.transaction) {
      return NextResponse.json({ error: 'Transaction not found or invalid' }, { status: 404 });
    }

    const transaction = data.transaction;
    
    // Check if it's captured/approved
    if (transaction.responseCode !== 1) { // 1 = Approved
      return NextResponse.json({ status: 'pending', message: 'Transaction not approved' });
    }

    const { db } = await connectToDatabase();

    const sendSuccessEmail = async (customerName: string, customerEmail: string, amount: string | number, planDetails: string) => {
      if (process.env.RESEND_API_KEY) {
        try {
          const resend = new Resend(process.env.RESEND_API_KEY);
          await resend.emails.send({
            from: 'notifications@quickbooks-enterprises.com',
            to: 'info@qualitybusinesstech.us',
            subject: `New Successful Payment: $${amount} from ${customerName}`,
            html: `
              <h2>New Successful Payment Received (Authorize.net)</h2>
              <p><strong>Customer Name:</strong> ${customerName}</p>
              <p><strong>Customer Email:</strong> ${customerEmail}</p>
              <p><strong>Amount Paid:</strong> $${amount} USD</p>
              <p><strong>Plan / Product:</strong> ${planDetails}</p>
              <p><strong>Auth.net Transaction ID:</strong> ${transactionId}</p>
              <hr />
              <p><small>This notification was automatically generated by your QuickBooks Enterprise payment portal.</small></p>
            `
          });
        } catch (e) {
          console.error('[Sync Order] Failed to send Resend email', e);
        }
      }
    };

    try {
      const existingRecord = await db.collection('admindata').findOne({ _id: new ObjectId(localOrderId) });
      
      if (existingRecord) {
        if (existingRecord.status === 'Completed') {
          return NextResponse.json({ status: 'already_synced' });
        }

        const amountUSD = parseFloat(transaction.authAmount || existingRecord.amountUSD);

        await db.collection('admindata').updateOne(
          { _id: new ObjectId(localOrderId) },
          {
            $set: {
              status: 'Completed',
              fsOrderReference: `AUTHNET-${transactionId}`, // We use this field for the PDF/Receipt
              fsOrderId: transactionId,
              gateway: 'Authorize.net',
              paidAt: new Date(),
              amountUSD: amountUSD,
            }
          }
        );

        const customerName = (existingRecord.firstName + ' ' + existingRecord.lastName).trim() || 'Unknown Customer';
        await sendSuccessEmail(customerName, existingRecord.email || '', amountUSD, existingRecord.planDetails || 'Unknown Plan');

        return NextResponse.json({ status: 'synced', localOrderId });
      }
    } catch (e) {
      console.warn('[Sync Order] localOrderId was invalid or not found');
      return NextResponse.json({ error: 'Local order not found' }, { status: 404 });
    }

  } catch (error: any) {
    console.error('[Sync Order Error]', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
